const data = {
  products: [
    {
      _id: '2',
      name: 'Nike Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description:
        'Made from soft, lightweight cotton in a relaxed fit, this Nike tee has a Futura logo printed on the chest, so you can bring that signature Nike style to any outfit.',
    },
    {
      _id: '3',
      name: 'Nike fit Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description:
        'Made from soft, lightweight cotton in a relaxed fit, this Nike tee has a Futura logo printed on the chest, so you can bring that signature Nike style to any outfit.',
    },
    {
      _id: '4',
      name: 'Nike fit Shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description:
        'Ready to rock the warmth and comfort of your favourite weekender hoodie, but need to keep your look clean? This Nike Tech Fleece hoodie strikes the right balance with a lightweight, low-profile design that packs in the heat without adding bulk. You can layer with ease whether youre lounging at home or making your city commute',
    },
    {
      _id: '5',
      name: 'Nike Air Force',
      category: 'Sneakers',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'The radiance lives on with the b-ball original. Crossing hardwood comfort with off-court flair, it puts a fresh spin on what you know best: era-echoing, 80s construction and nothing-but-net style.',
    },
    {
      _id: '6',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description:
        'Keep it simple, but dont settle for plain. This adidas t-shirt has just enough going on to be worthy of your wardrobe. Think of it as an understated canvas for making your trainers really pop. By buying cotton products from us, youre supporting more sustainable cotton farming',
    },
    {
      _id: '7',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description:
        'Keep it simple, but dont settle for plain. This adidas t-shirt has just enough going on to be worthy of your wardrobe. Think of it as an understated canvas for making your trainers really pop. By buying cotton products from us, youre supporting more sustainable cotton farming',
    },

    {
      _id: '10',
      name: 'Puma Fit Shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 159,
      countInStock: 12,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 15,
      description:
        'Made from soft, lightweight cotton in a relaxed fit, this Puma tee has a Futura logo printed on the chest, so you can bring that signature Puma style to any outfit.',
    },
    {
      _id: '11',
      name: 'Puma Sneakers',
      category: 'Sneakers',
      image: '/images/p11.jpg',
      price: 119,
      countInStock: 12,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 15,
      description:
        'Crafted with fine technology and futuristic design, Puma running shoes are surely here to uplift your style and track games. Kick-off on street and field in these shoes from the worlds leading and much-loved sports brand, Puma. Wear it with a T-shirt and shorts to look smart.',
    },

    {
      _id: '13',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p13.jpg',
      price: 259,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description:
        'Keep it simple, but dont settle for plain. This adidas t-shirt has just enough going on to be worthy of your wardrobe. Think of it as an understated canvas for making your trainers really pop. By buying cotton products from us, youre supporting more sustainable cotton farming',
    },
    {
      _id: '14',
      name: 'Adidas Sneakers',
      category: 'Sneakers',
      image: '/images/p14.jpg',
      price: 119,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description:
        'Crafted with fine technology and futuristic design, Adidas running shoes are surely here to uplift your style and track games. Kick-off on street and field in these shoes from the worlds leading and much-loved sports brand, Adidas. Wear it with a T-shirt and shorts to look smart.',
    },
    {
      _id: '15',
      name: 'Nike Sneakers',
      category: 'Sneakers',
      image: '/images/p15.jpg',
      price: 119,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description:
        'Crafted with fine technology and futuristic design, Nike running shoes are surely here to uplift your style and track games. Kick-off on street and field in these shoes from the worlds leading and much-loved sports brand, Nike. Wear it with a T-shirt and shorts to look smart.',
    },
    {
      _id: '16',
      name: 'Nike Sneakers',
      category: 'Sneakers',
      image: '/images/p16.jpg',
      price: 219,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description:
        'Crafted with fine technology and futuristic design, Nike running shoes are surely here to uplift your style and track games. Kick-off on street and field in these shoes from the worlds leading and much-loved sports brand, Nike. Wear it with a T-shirt and shorts to look smart.',
    },
  ],
};
export default data;
